import type { FoodItem, Order, AppNotification } from './types';

export const foodItems: FoodItem[] = [
  {
    id: '1',
    name: 'Veg Burger',
    description: 'Crispy vegetable patty with fresh lettuce, tomato, and house sauce in a toasted bun.',
    price: 60,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop&auto=format',
    prepTime: 8,
    available: true,
    ingredients: ['Vegetable patty', 'Lettuce', 'Tomato', 'Onion', 'House sauce', 'Toasted bun'],
    popular: true,
  },
  {
    id: '2',
    name: 'Grilled Sandwich',
    description: 'Toasted sandwich with cheese, fresh vegetables, and zesty mint chutney.',
    price: 40,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&h=400&fit=crop&auto=format',
    prepTime: 5,
    available: true,
    ingredients: ['Multigrain bread', 'Cheese', 'Cucumber', 'Tomato', 'Mint chutney'],
  },
  {
    id: '3',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato masala, served with coconut chutney and sambar.',
    price: 50,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop&auto=format',
    prepTime: 10,
    available: true,
    ingredients: ['Rice batter', 'Potato', 'Onion', 'Mustard seeds', 'Turmeric', 'Coconut chutney', 'Sambar'],
    popular: true,
  },
  {
    id: '4',
    name: 'Cold Coffee',
    description: 'Chilled blended coffee with milk and sugar, topped with a scoop of vanilla ice cream.',
    price: 30,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop&auto=format',
    prepTime: 3,
    available: true,
    ingredients: ['Espresso', 'Cold milk', 'Sugar', 'Vanilla ice cream', 'Ice'],
  },
  {
    id: '5',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed basmati rice with fresh vegetables, soy sauce, and aromatic spices.',
    price: 70,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop&auto=format',
    prepTime: 12,
    available: true,
    ingredients: ['Basmati rice', 'Mixed vegetables', 'Soy sauce', 'Ginger', 'Garlic', 'Spring onion'],
    popular: true,
  },
  {
    id: '6',
    name: 'Paneer Roll',
    description: 'Soft flatbread wrapped with spiced paneer tikka, crisp onions, and green chutney.',
    price: 55,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop&auto=format',
    prepTime: 7,
    available: true,
    ingredients: ['Flatbread', 'Paneer', 'Bell peppers', 'Onion', 'Green chutney', 'Spices'],
  },
  {
    id: '7',
    name: 'Lemon Juice',
    description: "Freshly squeezed lemon juice with a hint of mint and black salt. Cooling and bright.",
    price: 25,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&h=400&fit=crop&auto=format',
    prepTime: 2,
    available: true,
    ingredients: ['Lemon', 'Mint', 'Black salt', 'Sugar', 'Still water'],
  },
  {
    id: '8',
    name: 'French Fries',
    description: 'Golden crispy fries seasoned with our house blend of herbs and spices.',
    price: 45,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1573080496219-bb964701c2dc?w=600&h=400&fit=crop&auto=format',
    prepTime: 6,
    available: true,
    ingredients: ['Russet potato', 'Sunflower oil', 'House seasoning', 'Sea salt'],
    popular: true,
  },
  {
    id: '9',
    name: 'Idli Sambhar',
    description: 'Soft steamed rice cakes served with hot lentil soup and fresh coconut chutney.',
    price: 35,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1630409351217-bc4a8e7db56e?w=600&h=400&fit=crop&auto=format',
    prepTime: 5,
    available: true,
    ingredients: ['Rice batter', 'Urad dal', 'Toor dal', 'Vegetables', 'Coconut chutney'],
  },
  {
    id: '10',
    name: 'Gulab Jamun',
    description: 'Soft milk-solid dumplings soaked in rose-flavored sugar syrup. Served warm.',
    price: 30,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1666353781069-a87eff35d3e6?w=600&h=400&fit=crop&auto=format',
    prepTime: 2,
    available: true,
    ingredients: ['Milk solids', 'Refined flour', 'Sugar syrup', 'Rose water', 'Cardamom'],
  },
  {
    id: '11',
    name: 'Chole Bhature',
    description: 'Spiced chickpea curry served with fluffy, deep-fried bread. A canteen classic.',
    price: 65,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96ddb5?w=600&h=400&fit=crop&auto=format',
    prepTime: 15,
    available: false,
    ingredients: ['Chickpeas', 'Tomato', 'Onion', 'Spices', 'Refined flour', 'Ghee'],
  },
  {
    id: '12',
    name: 'Mango Lassi',
    description: 'Thick yogurt-based drink blended with ripe Alphonso mangoes and a touch of cardamom.',
    price: 40,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&h=400&fit=crop&auto=format',
    prepTime: 3,
    available: true,
    ingredients: ['Full-fat yogurt', 'Alphonso mango pulp', 'Sugar', 'Cardamom'],
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'SB1039',
    token: 'B-14',
    items: [
      { food: foodItems[2], quantity: 1 },
      { food: foodItems[6], quantity: 1 },
    ],
    total: 75,
    status: 'completed',
    placedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    estimatedReady: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000),
    queuePosition: 0,
  },
  {
    id: 'SB1031',
    token: 'A-08',
    items: [
      { food: foodItems[0], quantity: 2 },
      { food: foodItems[3], quantity: 1 },
    ],
    total: 150,
    status: 'completed',
    placedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    estimatedReady: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000),
    queuePosition: 0,
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'n1',
    message: 'Order #SB1039 is ready for pickup.',
    detail: 'Head to the canteen counter and show your token B-14.',
    type: 'success',
    time: '2 days ago',
    read: true,
  },
  {
    id: 'n2',
    message: 'Canteen crowd is currently moderate.',
    detail: 'Estimated wait time is around 14 minutes. Order ahead to save time.',
    type: 'warning',
    time: '45 min ago',
    read: false,
  },
  {
    id: 'n3',
    message: "Today's special: Chole Bhature is unavailable.",
    detail: 'We expect it to be back tomorrow. Sorry for the inconvenience.',
    type: 'info',
    time: '1 hour ago',
    read: false,
  },
];

export const hourlyForecast = [
  { time: '9 AM', level: 'LOW' as const, value: 18, wait: 5 },
  { time: '10 AM', level: 'LOW' as const, value: 28, wait: 7 },
  { time: '11 AM', level: 'MODERATE' as const, value: 52, wait: 12 },
  { time: '12 PM', level: 'HIGH' as const, value: 88, wait: 26 },
  { time: '1 PM', level: 'HIGH' as const, value: 95, wait: 30 },
  { time: '2 PM', level: 'MODERATE' as const, value: 58, wait: 14 },
  { time: '3 PM', level: 'LOW' as const, value: 22, wait: 6 },
  { time: '4 PM', level: 'LOW' as const, value: 15, wait: 4 },
];

export const adminOrders: Order[] = [
  {
    id: 'SB1042',
    token: 'A-27',
    items: [{ food: foodItems[0], quantity: 1 }, { food: foodItems[3], quantity: 1 }],
    total: 90,
    status: 'preparing',
    placedAt: new Date(Date.now() - 8 * 60 * 1000),
    estimatedReady: new Date(Date.now() + 6 * 60 * 1000),
    queuePosition: 4,
  },
  {
    id: 'SB1041',
    token: 'A-26',
    items: [{ food: foodItems[4], quantity: 1 }, { food: foodItems[7], quantity: 1 }],
    total: 115,
    status: 'ready',
    placedAt: new Date(Date.now() - 15 * 60 * 1000),
    estimatedReady: new Date(Date.now() - 3 * 60 * 1000),
    queuePosition: 0,
  },
  {
    id: 'SB1040',
    token: 'A-25',
    items: [{ food: foodItems[2], quantity: 2 }],
    total: 100,
    status: 'received',
    placedAt: new Date(Date.now() - 2 * 60 * 1000),
    estimatedReady: new Date(Date.now() + 10 * 60 * 1000),
    queuePosition: 6,
  },
  {
    id: 'SB1038',
    token: 'A-23',
    items: [{ food: foodItems[5], quantity: 1 }, { food: foodItems[11], quantity: 2 }],
    total: 135,
    status: 'completed',
    placedAt: new Date(Date.now() - 30 * 60 * 1000),
    estimatedReady: new Date(Date.now() - 22 * 60 * 1000),
    queuePosition: 0,
  },
];
